### ISSUE TITLE
Tree-CRF for hierarchical text categorization

### ISSUE THREAD

**Issue by usptact** [WladimirSidorenko/CRFSuite#8]
I am exploring different options to classify short texts (e.g. tweets) into an hierarchy of classes. There are 3 levels of hierarchy:
* top-level: ~20 classes
* mid-level: ~10-50 classes (depends on top-level class)
* lower-level: ~5-30 classes (depends on mid-level class)

Given a short text, I can extract specific features at each level. The tree structure is fixed; the problem is to predict the top, mid and low level classes given a short text.

Is Tree-CRF suitable for this kind of task? From literature, I see different techniques to hierarchical text categorization that employ all sorts of tricks. I didn't find any reference that uses a CRF for this task.

Thanks

**Comment by WladimirSidorenko** [comment]
If you have labels for your training instances, then you can basically use any graphical model, including CRFs, but unfortunately not this implementation, because you'll probably have different tagsets at different levels of granularity (which is not supported), and you'll apparently want to connect specific descendants (e.g., middle level labels) only to one of the ancestor nodes (e.g., one specific top-level class) (which is not supported either).

Nevertheless, you can still define a CRF model for this task.  I'd probably suggest that you first try implementing a prototype in some scripting language by yourself (maybe, look at pgmpy, can be that they already have everything you need), and I could give you a hand if you get stuck in some specific implementation questions. (The CRF model would actually be quite easy: just take the exponent of all features weights times their respective feature values, and divide it by the sum of the scores of all possible label assignments).  Although I'm not sure that you'll outperform other classification methods with it, but you can give a first try, and then refine the model, depending on the results you get.

**Comment by usptact** [comment]
Thanks a lot for the feedback! I am trying to find some solutions that are either ready to use or with little modification (yes, experimentation time is very short). One issue that I need to solve is that of error propagation. Say, the top-level classifier makes a mistake, the lower level classifiers won't have a chance to classify the input correctly either. A mechanism that deals with this problem would be great.

Speaking about graphical models, one of the ideas that I had is to build a hierarchical logistic regression model. The mid- and lower level model coefficients are influenced by their respective higher level model coefficients (as priors). In other words, going from general (top level) to more specific (low level). The leaf classes are likely getting trained on small data. In this setup, their coefficient priors would provide some start information. The beauty of the approach that during training, the information flows up and down the graph. I have little experience with pymc3 and more with Infer.NET. I am still exploring different options; will take a look at pgmpy.
